#!/bin/bash
# This program updates the .json using mongoexport and converts it to csv using the python script
# Requires mongoexport
# Requires a file called "auth" with the user and password separated by a space on the same line.

# terminate if fail
set -e 

if [[ ! -f mlab_auth ]] ; then
    echo 'File "mlab_auth" not found. Please create an authentication file before proceeding.'
		echo 'Format the authention file with the user, a space, then the password. E.g. "user password"'
    exit 1
fi

read -p "WARNING: Previous data will be overwritten. Do you wish to continue? (y/n): " CONT

if [ "$CONT" = "y" ]
then 
	echo Downloading files as json
	# read authentication file for mongo
	auth="mlab_auth"
	while read -r user password
	do
		rm *.csv *.json &> /dev/null || # try remove silently
		echo "User: $user"
		echo "Password: $password"
		# get data
		chat="mongoexport -h ds021701.mlab.com:21701 -d heroku_rb8x2bw9 -c chatmessages -u $user -p $password -o gameData/chatmessages.json"
		swaps="mongoexport -h ds021701.mlab.com:21701 -d heroku_rb8x2bw9 -c cardswaps -u $user -p $password -o gameData/cardswaps.json"
		state="mongoexport -h ds021701.mlab.com:21701 -d heroku_rb8x2bw9 -c states -u $user -p $password -o gameData/states.json"
		eval $chat
		eval $swaps
		eval $state
	done < "$auth"

	# convert to csv
#	echo Converting json to csv
#	python jsonToCSV.py
#	echo Conversion done
#	echo Copying to languageAnalysis/
#	cp hawkins_data/*Chinese* languageAnalysis/
	echo Done

else
	exit 1
fi

